### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by aboali1hassona** [glutanimate/highlight-search-results#8]
I find this error when I was opening the Anki windows. version 2.48 

Anki 2.1.48 (fb07bad3) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-09-26 17:26:35

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 541, in handler
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\1783260740\__init__.py", line 180, in cb
    rendered = info[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by glutanimate** [comment]
Hi there, Thanks for the report! Based on the error message it seems to be an issue with the following add-on (1783260740): [Add Cards - Web Browser](https://ankiweb.net/shared/info/1783260740). It seems like the issue has been reported here: https://github.com/fonol/add-browser/issues/8. Until a fix is out, disabling the add-on in question would likely be the best option.

**Comment by aboali1hassona** [comment]
THanks
